# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce905b5d80769b6ec587d865b937640baa6b4e8478b3c2853684c65b81521217c026074f212f3b177d6167482596ebf2c8196b29944801ac45869719eb0b1b1e
  facebook_app_id: 346217325558292
  facebook_app_secret: 32f957ac5fb2592d9e43b3798570c8cd
  twitter_key: nHhz6yKEPKxQmTOyrs4OCRv7I
  twitter_secret: xozlSCPYmlGherIOMF3Ss4t0CVPwK5Vb2h3QJKbRulRlgAwtqh 
  gmail_name: domfoto72@gmail.com
  gmail_password: y9788886

test:
  secret_key_base: 06b706ab2b00545ad5f4e92eead9db269cc27a93eba21127a156ee5d001faf5089f241577206d4d48eb8efe95114d6138002c8b84f547787fd67c73df77cd5af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>


staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

